# Generated by Django 4.2.4 on 2023-08-26 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название региона')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название учебного заведения')),
                ('description', models.TextField(verbose_name='Описание учебного заведения')),
                ('education_type', models.CharField(choices=[('S', 'Общеобразовательное учреждение'), ('U', 'Высшее учебное заведение'), ('C', 'Среднее профессиональное учреждение')], max_length=1, verbose_name='Тип учебного заведения')),
                ('web_site_url', models.TextField(verbose_name='Адрес сайта учебного заведения')),
                ('contacts', models.TextField(verbose_name='Контакты учебного заведения')),
                ('address', models.TextField(verbose_name='Адрес учебного заведения')),
                ('director_name', models.CharField(default='', max_length=255, verbose_name='Имя директора')),
                ('location', models.CharField(max_length=255, verbose_name='Координаты учебного заведения')),
                ('region_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.region')),
            ],
        ),
    ]
