# Generated by Django 4.2.4 on 2023-08-26 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='education_type',
        ),
        migrations.AlterField(
            model_name='education',
            name='region_id',
            field=models.CharField(choices=[('G', 'Грозненский район'), ('U', 'Урусмартановский район'), ('V', 'Веденский район'), ('I', 'Итумкалинский район')], max_length=1, verbose_name='Район учебного заведения'),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
