# Generated by Django 4.2.4 on 2023-08-26 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_education_education_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='region_id',
            new_name='region',
        ),
    ]
