# Generated by Django 4.2.4 on 2023-08-26 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_region_id_education_region'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Образовательное учреждение', 'verbose_name_plural': 'Образовательные учреждения'},
        ),
    ]
