# Generated by Django 4.2.4 on 2023-08-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_education_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='region',
            field=models.CharField(choices=[('GRZR', 'Грозненский район'), ('URUS', 'Урус-Мартановский район'), ('VEDN', 'Веденский район'), ('ITUM', 'Итум-Калинский район'), ('SHAL', 'Шалинский район'), ('SHAT', 'Шатойский район'), ('SHAR', 'Шаройский район'), ('KURC', 'Курчалоевский район'), ('SHEL', 'Шелковской район'), ('SERN', 'Серноводский район'), ('ACHM', 'Ачхой-Мартановский'), ('NTRK', 'Надтеречный район'), ('NAUR', 'Наурский район'), ('GUMS', 'Гудермесский район'), ('NOJU', 'Ножай-Юртовский район'), ('GROZ', 'Грозный'), ('ARGN', 'Аргун')], max_length=4, verbose_name='Район учебного заведения'),
        ),
    ]
