# Generated by Django 4.2.4 on 2023-08-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_education_address_alter_education_contacts_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='contacts',
            field=models.CharField(max_length=255, null=True, verbose_name='Контакты учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='director_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Имя директора'),
        ),
        migrations.AlterField(
            model_name='education',
            name='web_site_url',
            field=models.CharField(max_length=255, null=True, verbose_name='Адрес сайта учебного заведения'),
        ),
    ]
