# Generated by Django 4.2.4 on 2023-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_education_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(null=True, verbose_name='Описание учебного заведения'),
        ),
    ]
