# Generated by Django 4.2.4 on 2023-08-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_education_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='contacts',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Контакты учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='director_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя директора'),
        ),
        migrations.AlterField(
            model_name='education',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Электронная почта учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название учебного заведения'),
        ),
        migrations.AlterField(
            model_name='education',
            name='web_site_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес сайта учебного заведения'),
        ),
    ]
