# Generated by Django 4.2.4 on 2023-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_education_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Название учебного заведения'),
        ),
    ]
