# Generated by Django 4.2.5 on 2023-09-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_education_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='image_one',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='education',
            name='image_three',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='education',
            name='image_two',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
