# Generated by Django 4.2.5 on 2023-09-24 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_education_image_one_education_image_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
