# Generated by Django 4.2.5 on 2023-09-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_education_image_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='image_one',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image_three',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
        migrations.AlterField(
            model_name='education',
            name='image_two',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
